### ISSUE TITLE
20-etcd-service-manager.conf -> missing cgroup-driver

### ISSUE THREAD

**Issue by ReSearchITEng** [mbert/kubeadm2ha#14]
20-etcd-service-manager.conf is missing the "--cgroup-driver=systemd"
BTW, FYI, starting 1.11 this setting is handled automatically by kubeadm, but this step is before calling kubeadm.

"kubeadm now detects the Docker cgroup driver and starts the kubelet with the matching driver. This eliminates a common error experienced by new users in when the Docker cgroup driver is not the same as the one set for the kubelet due to different Linux distributions setting different cgroup drivers for Docker, making it hard to start the kubelet properly. (#64347, @neolit123)"

The prepare-nodes cgroup driver part does not apply to this because:
a) 20-etcd-service-manager.conf overrides the 10-kubeadm.conf
b) the prepare-nodes code won't do anything any longer, as 10-kubeadm.conf no longer holds the "cgroup-driver" string.

**Comment by mbert** [comment]
I'll have to investigate this (but not soon, unfortunately). The code as it is worked in my environment (K8s 1.11, RHELish, version 7.x). If there are problems in other distros, some additional information would be helpful.

**Comment by ReSearchITEng** [comment]
I am on RHEL/CentOS also, and for sure we need "--cgroup-driver=systemd" . I've added it and all ok.

**Comment by neolit123** [comment]
since k8s 1.11 the `--cgroup-driver` flag for the kubelet is added automatically, not in 10-kubeadm.conf, but rather in a file called `/var/lib/kubelet/kubeadm-flags.env`

```
# This is a file that "kubeadm init" and "kubeadm join" generates at runtime, populating
the KUBELET_KUBEADM_ARGS variable dynamically
```

there is yet another file that can be used for user values:
```
# This is a file that the user can use for overrides of the kubelet args as a last resort. Preferably,
#the user should use the .NodeRegistration.KubeletExtraArgs object in the configuration files instead.
# KUBELET_EXTRA_ARGS should be sourced from this file.
EnvironmentFile=-/etc/default/kubelet
```

https://kubernetes.io/docs/setup/independent/kubelet-integration/#the-kubelet-drop-in-file-for-systemd

hope that helps.
