### ISSUE TITLE
modprobe ip_vs - suggestion

### ISSUE THREAD

**Issue by ReSearchITEng** [mbert/kubeadm2ha#15]
"/root/join-worker-node.sh" - WARNING
   (ignorable, as it should be done as a prereq maybe)
   RequiredIPVSKernelModulesAvailable]: the IPVS proxier will not be used, because the following required kernel modules are not loaded: [ip_vs_wrr ip_vs_sh ip_vs ip_vs_rr]
     add:
    modprobe ip_vs_wrr ip_vs_sh ip_vs ip_vs_rr
    But also make them persistent.

    - name: load ip_vs kernel modules
      modprobe: name={{ item }} state=present
      with_items:
      - ip_vs_wrr
      - ip_vs_rr
      - ip_vs_sh
      - ip_vs

    - name: persist ip_vs kernel modules
      copy:
        path: /etc/modules-load.d/ip_vs.conf
          content: |
            ip_vs_wrr
            ip_vs_rr
            ip_vs_sh
            ip_vs

**Comment by mbert** [comment]
Maybe 'prerequisites' section in README.md? 
Kernel configuration is out of scope since often the places to configure these things persistently differs between distros.

**Comment by ReSearchITEng** [comment]
yes, you are right.
