### ISSUE TITLE
bridge-nf-call-iptables - suggestion

### ISSUE THREAD

**Issue by ReSearchITEng** [mbert/kubeadm2ha#16]
"/root/join-worker-node.sh" - FATAL ERROR
  (ignorable, as it should be done as a prereq maybe)
  [ERROR FileContent--proc-sys-net-bridge-bridge-nf-call-iptables]: /proc/sys/net/bridge/bridge-nf-call-iptables contents are not set to 1
      echo "1" > /proc/sys/net/bridge/bridge-nf-call-iptables
      but also make it persistent

**Comment by mbert** [comment]
That, too, should go into a 'prerequisites' section in README.md
