### ISSUE TITLE
kubeadm token create  --print-join-command - suggestion

### ISSUE THREAD

**Issue by ReSearchITEng** [mbert/kubeadm2ha#18]
I noticed there is a nice option "--print-join-command" , which provides the 
kubeadm token create --print-join-command
I0914 14:11:14.396695   3948 feature_gate.go:230] feature gates: &{map[]}
kubeadm join 10.1.3.2:6443 --token aaaaaa.bbbbbbbbbbbbbbbb --discovery-token-ca-cert-hash sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb

You may want to look at it for the join-token role, which is quite complicated now with the openssl option.

**Comment by mbert** [comment]
Looks very good. This, too, goes on my list for November (I don't expect to have the time for this any time before that).
