### ISSUE TITLE
Different kubeadm-init Configs

### ISSUE THREAD

**Issue by discostur** [mbert/kubeadm2ha#7]
Hi,

why are you using different kubeadm-init.yaml.j2 tempalte files for master / secondary? I just ran your playbook and you should always set "endpoint-reconciler-type" for the apiserver (not only on the secondaries but also on the master):

```
apiServerExtraArgs:
  {% if KUBERNETES_VERSION | match('^1\.8') %}apiserver-count: "{{ groups['masters'] | length }}"{% else %}endpoint-reconciler-type: "lease"{% endif %}
``` 

You should always use the "global" templates/kubeadm-init.yaml.j2 file:
[template/kubeadm-init.yaml.j2](https://raw.githubusercontent.com/mbert/kubeadm2ha/master/ansible/templates/kubeadm-init.yaml.j2)

**Comment by mbert** [comment]
Good you found this. The template for the primary master should have been deleted, I had meant to move it to ./templates entirely. "Unfortunately" this never lead to any problems and was hence unnoticed.

The 'endpoint-reconciler-type' was set for K8s versions > 1.8, it may be safe to drop support for older versions now. I will have change and test this.

**Comment by mbert** [comment]
Good you found this. The template for the primary master should have been deleted, I had meant to move it to ./templates entirely. "Unfortunately" this never lead to any problems and was hence unnoticed.

The 'endpoint-reconciler-type' was set for K8s versions > 1.8, it may be safe to drop support for older versions now. I will have change and test this.
