### ISSUE TITLE
Role: ha-settings improvements

### ISSUE THREAD

**Issue by discostur** [mbert/kubeadm2ha#8]
Your are doing some steps twice, which is not necessary (seems like a copy paste error for me):

[ha-settings/tasks/main.yaml](https://github.com/mbert/kubeadm2ha/blob/master/ansible/roles/ha-settings/tasks/main.yaml)

- Get current kube-proxy settings
- Edit current kube-proxy settings to use the virtual IP instead of the host IP
- Apply edited kube-proxy settings
- Force restart of all kube-proxy pods

**Comment by mbert** [comment]
Correct. That came in in a8aa1e6bb37078f45644cad5e425139dd31c2031, good you found it.
