### ISSUE TITLE
Join worker nodes MASTER_VIP

### ISSUE THREAD

**Issue by discostur** [mbert/kubeadm2ha#9]
You should join all worker (minions) nodes via the MASTER_VIP and not via the primary master IP:

[join-token/templates/join-worker-node.sh.j2](https://github.com/mbert/kubeadm2ha/blob/master/ansible/roles/join-token/templates/join-worker-node.sh.j2)
```
kubeadm join --token {{ TOKEN.stdout }} {{ MASTER_VIP }}:6443 --discovery-token-ca-cert-hash sha256:{{ HASH.stdout }}
```

**Comment by mbert** [comment]
Thanks for this (and the other comments). I'll look into this next week when I'm back from the KubeConn :)
